services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - app-network
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=Assurnet2024!SecureJWTKey#OrchestrationPlatform
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=assurnet_orchestration
      - DB_USER=postgres
      - DB_PASSWORD=AssurnetDB2024!
      - SMTP_HOST=smtp.office365.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=orchestration@assurnet.com
      - SMTP_PASS=YourEmailPassword
      - ADMIN_EMAILS=admin@assurnet.com,it@assurnet.com
    depends_on:
      - database
    volumes:
      - ./logs:/app/logs
      - ~/.ssh:/root/.ssh:ro
    networks:
      - app-network

  database:
    image: postgres:15
    environment:
      - POSTGRES_DB=assurnet_orchestration
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AssurnetDB2024!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge